### ISSUE TITLE
How to rename username in login screen?

### ISSUE THREAD

**Issue by coder-lg** [Renovamen/playground-macos#11]
I am new here, and I want to use this theme. How can I rename the Username in the login screen?

**Comment by Renovamen** [comment]
In `src/configs/user.js`:

https://github.com/Renovamen/playground-macos/blob/0b0892f5ecb0a2e0716829e12c22e5d696589268/src/configs/user.js#L2

**Comment by coder-lg** [comment]
thanks :smile:
