### ISSUE TITLE
太酷了！

### ISSUE THREAD

**Issue by YuYanzy** [Renovamen/playground-macos#12]
这个项目出现在我的首推页面上，看了一下非常赞！2333，顺便也瞅了一下作者的博客和其他项目，感觉都非常有意思！祝好~

**Comment by niusz** [comment]
首推页面是哪里的页面呀？

**Comment by YuYanzy** [comment]
我用了一个chrome的扩展页插件 githuber https://github.com/zhuowenli/githuber

**Comment by niusz** [comment]
> 我用了一个chrome的扩展页插件 githuber https://github.com/zhuowenli/githuber

谢谢

**Comment by soap-man** [comment]
> 这个项目出现在我的首推页面上，看了一下非常赞！2333，顺便也瞅了一下作者的博客和其他项目，感觉都非常有意思！祝好~

没看明白，这个可以干嘛

**Comment by YuYanzy** [comment]
> > 这个项目出现在我的首推页面上，看了一下非常赞！2333，顺便也瞅了一下作者的博客和其他项目，感觉都非常有意思！祝好~
> 
> 没看明白，这个可以干嘛

好玩啊！这多有意思啊！好玩就完事了！

**Comment by Renovamen** [comment]
多谢多谢，祝好
