### ISSUE TITLE
renaming the tab

### ISSUE THREAD

**Issue by coder-lg** [Renovamen/playground-macos#13]
how do you rename the tab?

**Comment by Renovamen** [comment]
Which tab?

**Comment by coder-lg** [comment]
the main tab in the browser

**Comment by Renovamen** [comment]
In [`src/configs/websites.js`](https://github.com/Renovamen/playground-macos/blob/main/src/configs/websites.js). 

Most of the personal information can be configurated in folder [`src/configs/`](https://github.com/Renovamen/playground-macos/blob/main/src/configs).

**Comment by coder-lg** [comment]
thanks

**Comment by coder-lg** [comment]
I was asking, how do you rename the site's tab name in Google Chrome or, in my case, Vivaldi

**Comment by coder-lg** [comment]
also how to change the favicon too

**Comment by Renovamen** [comment]
Oh I got it. In `public/index.html`:

https://github.com/Renovamen/playground-macos/blob/0b0892f5ecb0a2e0716829e12c22e5d696589268/public/index.html#L27

**Comment by Renovamen** [comment]
> also how to change the favicon too

Set your favicon here:

https://github.com/Renovamen/playground-macos/blob/0b0892f5ecb0a2e0716829e12c22e5d696589268/public/index.html#L12

and here:

https://github.com/Renovamen/playground-macos/blob/0b0892f5ecb0a2e0716829e12c22e5d696589268/public/manifest.json#L1-L25

**Comment by coder-lg** [comment]
Thanks
