### ISSUE TITLE
请问登录页面能实现输入密码访问吗

### ISSUE THREAD

**Issue by IILee5** [Renovamen/playground-macos#18]
让输入的密码与我们的配置来比对，而不是只作为一个界面来展示它

**Comment by Renovamen** [comment]
抱歉那么晚回复，如果只是想实现一个输密码才能进的效果的话，大概给这一行加个判等就好：

https://github.com/Renovamen/playground-macos/blob/28974b0561fa6699331929a2fc3fcaa2ccec1474/src/pages/Login.js#L12

如果真的想要加密（看源码也看不到密码的那种），可以考虑搜一搜用于加密的库（虽然我也不知道啥库合适）？

**Comment by IILee5** [comment]
哈哈哈，我正在实践，谢谢回复啦
