### ISSUE TITLE
Failed to compile 编译好像有点问题

### ISSUE THREAD

**Issue by landlordlycat** [Renovamen/playground-macos#20]
![image](https://user-images.githubusercontent.com/39334446/126766326-adad3909-5326-4d1e-b6ba-cecbf565067f.png)
出现这个，但是我刷新又能出现画面。但是一闪而过又回到了上图的情况

**Comment by Renovamen** [comment]
我搜了一下，大概是不同系统下换行符不一致的问题，这里有一些解决方案：https://juejin.cn/post/6844904069304156168

**Comment by landlordlycat** [comment]
谢谢大佬。
