### ISSUE TITLE
md渲染问题

### ISSUE THREAD

**Issue by IILee5** [Renovamen/playground-macos#21]
源文件样式：
![image](https://user-images.githubusercontent.com/40862062/129869647-d68ec0f0-8f3e-4791-b741-65a8e9311873.png)
正常渲染后的样式：
![image](https://user-images.githubusercontent.com/40862062/129869720-6fcbac00-7d00-48fb-8e11-38f692622da1.png)
macos主页渲染后样式：
![image](https://user-images.githubusercontent.com/40862062/129869866-49371748-0521-4bf8-ae5c-a4dcda4f6ba0.png)
大概问题就是，原生的html语法再主页项目栏内不兼容，导致主页看起来很怪

**Comment by Renovamen** [comment]
我用了 [react-markdown](https://github.com/remarkjs/react-markdown) 来渲染 Markdown，它默认会忽视掉 Markdown 里的 HTML（为了安全性）。但如果想支持 HTML 语法的话，参考它的[文档](https://github.com/remarkjs/react-markdown#appendix-a-html-in-markdown)装一个插件 [`rehype-raw`](https://github.com/rehypejs/rehype-raw) 和修改下面这段代码就可以了：

https://github.com/Renovamen/playground-macos/blob/b7f0bd0b325882ae10d5aec19e700b43fec964d0/src/components/apps/Bear.tsx#L206-L211

因为我目前没有这个需求，同时考虑到打包大小，我暂时应该不会装这个插件，非常感谢。

**Comment by IILee5** [comment]
我昨天尝试在`react-markdown`中加入`rehype-raw`插件，但是渲染失败了，可能是方式不太对。我会去尝试解决它，感谢您的回复😄️那我把这个issues关了，自己研究一下加进去

**Comment by Renovamen** [comment]
我刚试了一下是可以的 😂，有什么报错吗？

**Comment by IILee5** [comment]
😄️可以把相关代码帖一下吗大佬，我react不是特别熟悉，可能也是代码写错了哈哈

**Comment by Renovamen** [comment]
```diff
+ import rehypeRaw from "rehype-raw";

<ReactMarkdown 
   children={this.state.storeMd[this.props.id]} 
   linkTarget="_blank" 
   remarkPlugins={[gfm]} 
+  rehypePlugins={[rehypeRaw]}
   components={Highlighter(this.props.dark as boolean)} 
 />
```

如果是 typescript 报错的话，用我最新的代码试试？我刚升级了一下依赖。

**Comment by IILee5** [comment]
![image](https://user-images.githubusercontent.com/40862062/130047800-f8a21f72-a1b2-420e-b2e8-e9c0415ff00d.png)
生效了！果然是我代码写错了。
大佬是这样的
```js
remarkPlugins={[gfm]} 
rehypePlugins={[rehypeRaw]}
```
而我自己一开始是这样子的
```js
remarkPlugins={[gfm,rehypeRaw]}
```
我以为这里是个数组，受教了哈哈

**Comment by Renovamen** [comment]
> 我以为这里是个数组，受教了哈哈

这的确是个数组，但这俩 props 不一样啊，一个是 `remarkPlugins` 一个是 `rehypePlugins`，所以得分开传 😂

**Comment by IILee5** [comment]
> 这的确是个数组，但这俩 props 不一样啊，一个是 `remarkPlugins` 一个是 `rehypePlugins`，所以得分开传 😂

感谢大佬哈哈，这模板真的太炫酷了👍，情不自禁的加了很多乱七八糟的东西上去
