### ISSUE TITLE
Use css-property filter to implent brightness justify feature

### ISSUE THREAD

**Issue by jhonleeee** [Renovamen/playground-macos#4]
使用 redux+css： filter( brightness:( 0.x %); ) 应用在界面上就可以超偷鸡地实现控制栏里Brightness的调节功能啦~ 最好加个限制，否则调到0就完全看不到就尴尬了hhh  
因为实在太简单所以不好意思提PR，希望龙大人采纳，嗷呜嗷呜🐲

**Comment by Renovamen** [comment]
啊这对本菜鸡来说并不简单啊喂，想提 PR 就提嗷！不然我就明天起床了试一试

不过龙大人还是过于中二和羞耻了当不起当不起😂
